### ISSUE TITLE
What should be the input of GLMGam?

### ISSUE THREAD

**Issue by BW15061999** [PeterZZQ/CeSpGRN#1]
Hi,
I reshape the THP-1 example thetas matrix into a 2D array and load the pt_slingshot file as the input of GLMGam, but it returns the error message below.
`ValueError: operands could not be broadcast together with shapes (960,) (960,2025)`

I wonder what should be correct form of the input of GLMGam? Thank you!

[pt_slingshot.csv](https://github.com/PeterZZQ/CeSpGRN/files/8486084/pt_slingshot.csv)

**Comment by PeterZZQ** [comment]
Hi,

The reason for that error is that one input has a single dimension `(960, )` and another has double dimensions `(960, 2025)`. You need to transform the single dimension to double dimensions. I'm guessing that the shape `(960, )` refers to the `pt_slingshot`? If it is the case, you just need to reshape the `pt_slingshot` into `(960, 1)` (double dimensions).

**Comment by BW15061999** [comment]
Hi,

The `pt_slingshot` input file is already in (960,1), and I try to return the (960,) matrix and find it only contain integer 1 instead of pseudotime-related data. 

Here is the error message

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [6], in <cell line: 13>()
     10 exog, endog = sm.add_constant(pt),thetas
     12 model_full = sm.GLMGam(endog = endog, exog = exog, smoother = spline)
---> 13 res_full = model_full.fit()

File ~/Downloads/Softwares/Anaconda/envs/sklearn/lib/python3.10/site-packages/statsmodels/gam/generalized_additive_model.py:634, in GLMGam.fit(self, start_params, maxiter, method, tol, scale, cov_type, cov_kwds, use_t, full_output, disp, max_start_irls, **kwargs)
    630 # TODO: alpha not allowed yet, but is in `_fit_pirls`
    631 # alpha = self._check_alpha()
    633 if method.lower() in ['pirls', 'irls']:
--> 634     res = self._fit_pirls(self.alpha, start_params=start_params,
    635                           maxiter=maxiter, tol=tol, scale=scale,
    636                           cov_type=cov_type, cov_kwds=cov_kwds,
    637                           use_t=use_t, **kwargs)
    638 else:
    639     if max_start_irls > 0 and (start_params is None):

File ~/Downloads/Softwares/Anaconda/envs/sklearn/lib/python3.10/site-packages/statsmodels/gam/generalized_additive_model.py:715, in GLMGam._fit_pirls(self, alpha, start_params, maxiter, tol, scale, cov_type, cov_kwds, use_t, weights)
    709     iteration = 0
    711 for iteration in range(maxiter):
    712 
    713     # TODO: is this equivalent to point 1 of page 136:
    714     # w = 1 / (V(mu) * g'(mu))  ?
--> 715     self.weights = self.data_weights * self.family.weights(mu)
    717     # TODO: is this equivalent to point 1 of page 136:
    718     # z = g(mu)(y - mu) + X beta  ?
    719     wlsendog = (lin_pred + self.family.link.deriv(mu) * (endog - mu)
    720                 - self._offset_exposure)

ValueError: operands could not be broadcast together with shapes (960,) (960,2025) 
```

**Comment by PeterZZQ** [comment]
Hi, please try the following sample code

``` {python}
pt = pd.read_csv("pt_slingshot.csv", header = None)
# where you load in the 2d theta matrix
thetas_df = pd.read_csv("xxx.csv")
pt.columns = ["Traj0"]
de_edges = de.de_analy(thetas_df, pt, distri = "normal", fdr_correct = True)
print(len(de_edges["Traj0"]))
figs = de.de_plot(thetas_df, pt, de_edges, figsize = (20,80), n_genes = 40)
```

**Comment by BW15061999** [comment]
Hi, Thank you! 
This code works, but still the `GAM_pt` function returns the same error with the input of `de_analy`.

 Here is a part of the code in the `GAM_pt` function
```
from statsmodels.gam.api import GLMGam, BSplines, CyclicCubicSplines

    exog, endog = sm.add_constant(pse_t),expr
    # calculate full model
    model_full = sm.GLMGam(endog = endog, exog = exog, smoother = spline, family = family)
    try:
        res_full = model_full.fit()
    except:
        # print("The gene expression is mostly zero")
        return None, None, None
```

the error seems to generate in `model_full.fit()`

**Comment by PeterZZQ** [comment]
Could you show me what your code is like? I just rerun the code and here is the screenshot of what I ran:
<img width="996" alt="image" src="https://user-images.githubusercontent.com/37580703/163507753-47221360-e708-4974-83c0-58a84f39cb46.png">

**Comment by BW15061999** [comment]
![Screenshot from 2022-04-15 10-27-32](https://user-images.githubusercontent.com/52130151/163508382-413f18ac-c934-4231-8383-da15bbd708b7.png)
![Screenshot from 2022-04-15 10-29-10](https://user-images.githubusercontent.com/52130151/163508520-2fa4c24f-e686-40a8-a4d2-7a6c067ce512.png)

**Comment by PeterZZQ** [comment]
Oh I see, you just want to extract that part and run. If you check the function `de_analy`, this is what we called
```
gene_pred, gene_null, p_val = GAM_pt(pse_t, gene_dynamic, smooth='BSplines', df = 4, degree = 3, family=sm.families.Gaussian(link = sm.families.links.log()))
```
And the `pse_t` and `gene_dynamic` are calculated using
```
gene_dynamic = np.squeeze(X_traj.iloc[:,idx])
pse_t = np.arange(gene_dynamic.shape[0])[:,None]
```
So the gene_dynamic should have the shape (960, ) and the pse_t should have the shape (960, 1).

**Comment by BW15061999** [comment]
Thank you! This time works!

So the function `GAM_pt` calculates a gene per time?
I thought this function works like `gam` in R which fits multiple genes in a time

**Comment by PeterZZQ** [comment]
Yes, it just fits one gene per time, and you need to loop through all genes.

**Comment by BW15061999** [comment]
Thank you for your help!@[PeterZZQ](https://github.com/PeterZZQ)
